### ISSUE TITLE
Save Button Missing?

### ISSUE THREAD

**Issue by CharlieBravoAcutal** [Ylianst/HTCommander#21]
Installed on windows 11 machine.  Based on the introduction video it appears there should be a save button at the bottom of the channel group editing window.  I do not see a way to save an edit.  My apologies if this has been brought up previously, if so I could not find any reference to this.   

Any assistance is appreciated.  

Thank you.

What I see
![Image](https://github.com/user-attachments/assets/d97524ec-e6bb-46fc-938d-9e2b7c4f949a)

Screenshot from intro video

![Image](https://github.com/user-attachments/assets/8ac60764-8153-4bfe-a907-b82caf28dfaa)

**Comment by Ylianst** [comment]
Oh! That is super weird. I will take a look at this in the coming days. Very interesting!

**Comment by Ylianst** [comment]
@CharlieBravoAcutal  - I released version 0.42 with a possible fix for this. If you can update and let me know if it works, that would be great. Thanks.

**Comment by CharlieBravoAcutal** [comment]
I will.  Give me a couple (hopefully sooner).  Thank you.

**Comment by CharlieBravoAcutal** [comment]
> [@CharlieBravoAcutal](https://github.com/CharlieBravoAcutal) - I released version 0.42 with a possible fix for this. If you can update and let me know if it works, that would be great. Thanks.

No luck.

![Image](https://github.com/user-attachments/assets/92b5c97b-6665-4f64-88c2-e96d957ca397)
![Image](https://github.com/user-attachments/assets/42ed23bd-3414-471e-b16c-553fed5f9804)

**Comment by Ylianst** [comment]
Arg! Ok, I will try something different. Thanks for the report. I can't reproduce this, but will re-code this dialog box differently.

**Comment by CharlieBravoAcutal** [comment]
> Arg! Ok, I will try something different. Thanks for the report. I can't reproduce this, but will re-code this dialog box differently.
I bought a bluetooth transmitter for my desktop to do some troubleshooting and installed the software on it with no issues.  The save button is present on my desktop.  Still no luck on my laptop which is my primary computer.

**Comment by Ylianst** [comment]
@CharlieBravoAcutal - Version 0.43 is out, let me know if this works.

**Comment by CharlieBravoAcutal** [comment]
> [@CharlieBravoAcutal](https://github.com/CharlieBravoAcutal) - Version 0.43 is out, let me know if this works.

That appears to have fixed the issue.  Thank you!

![Image](https://github.com/user-attachments/assets/5c456e9e-fc05-4a30-afc3-478723295170)

**Comment by Ylianst** [comment]
Nice! Thanks for reporting back.

**Comment by CharlieBravoAcutal** [comment]
One quick question, when I minimize the app I cannot bring it back.  Is that typical?  I have to end task and reopen the app.

**Comment by Ylianst** [comment]
Uncheck the "System tray" option and let me know if that fixes it

<img width="418" height="265" alt="Image" src="https://github.com/user-attachments/assets/ea89f785-fa17-4f7b-9963-1e2cad3c62ea" />

**Comment by CharlieBravoAcutal** [comment]
Thank you!  That was it.

**Comment by Ylianst** [comment]
Nice @CharlieBravoAcutal - Thanks for reporting back. If using the system tray, HTCommander will stay running in the background and pop-up notifications when you get a APRS message.
